
name: Ubuntu+jdk1.8

on: push


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Cache Maven packages
      id: cache-maven-m2
      uses: actions/cache@v2
      with:
       path: ~/.m2
       key: ${{ runner.os }}-pr-builder
    - name: Check cache hit
      if: steps.cache-maven-m2.outputs.cache-hit == 'true'
      run: echo "cache hit status " ${{steps.cache-maven-m2.outputs.cache-hit}}
    - name: Build with Maven
      run: |
        wget https://gist.github.com/janakamarasena/d84e5383805a352cd186121f2f491435/raw/12c8dcf61839da6804c8f0d5188259d580faaf43/builder_test.sh
        bash builder_test.sh
