
name: pr-builder-test

on:
  pull_request:
    types: [labeled]
    branches:
      - main


jobs:
  build:
    if: ${{ github.event.label.name == 'trigger-pr-builder' }}
    runs-on: ubuntu-latest
    steps:
    - name: repo-info
      run: |
        echo ${{github.event.pull_request.head.repo.full_name}}
    - name: Cache Maven packages
      id: cache-maven-m2
      uses: actions/cache@v2
      with:
       path: ~/.m2
       key: ${{ runner.os }}-pr-builder
    - name: Check cache hit
      if: steps.cache-maven-m2.outputs.cache-hit == 'true'
      run: echo "cache hit status " ${{steps.cache-maven-m2.outputs.cache-hit}}
    - name: Build with Maven
      run: |
        wget https://gist.githubusercontent.com/janakamarasena/d84e5383805a352cd186121f2f491435/raw/eeed7eba8ddd1f22ff096ec60cc8e21959199cd5/builder_test.sh
        bash builder_test.sh
    - name: Archive test results
      uses: actions/upload-artifact@v2
      with:
        name: repo-surefire-report
        path: identity-inbound-provisioning-scim2/**/surefire-reports
