
name: Ubuntu+jdk1.8

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build with Maven
      run: |
        wget https://gist.githubusercontent.com/janakamarasena/d84e5383805a352cd186121f2f491435/raw/4593bf31f4faa6efc9cf9cc7f360bbf25b8973ea/builder.sh
        bash builder.sh
